import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import './globals.css'
import { Provider as BalancerProvider } from 'react-wrap-balancer'

const quickSand = Quicksand({
    // weight: ['400', '700'],
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            {/* <BalancerProvider> */}
            <body className={'quicksand'}>{children}</body>
            {/* </BalancerProvider> */}
        </html>
    )
}
